version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=hexstody
      - POSTGRES_USER=hexstody
      - POSTGRES_DB=hexstody

  service:
    image: hexstody:latest
    ports:
      - "8081:8081"
    hostname: kolliderhedge
    environment:
      - HEXSTODY_POSTGRES=postgres://hexstody:hexstody@postgres:5432/hexstody
      - HEXSTODY_PORT=8081
      - RUST_LOG=hexstody::api,hexstody=debug,hexstody_domain=debug
      # Set it via .env file
      - HEXSTODY_API_KEY=$HEXSTODY_API_KEY
    command: /wait-for-it.sh postgres:5432 -- /hexstody-hot serve
    links:
      - postgres