[package]
name = "hexstody-sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hexstody_sig"
path = "src/lib.rs"

[dependencies]
p256 ="0.11.1"
rand_core = { version = "0.6.3", features = ["std"] }
