[default]

public_api_enabled = true
public_api_port = 9800
public_api_static_path = "../hexstody-public/static"
public_api_template_path = "../hexstody-public/templates"

operator_api_enabled = true
operator_api_port = 9801
operator_api_static_path = "../hexstody-operator/static"
operator_api_template_path = "../hexstody-operator/templates"
